### ISSUE TITLE
Wrong Calculation

### ISSUE THREAD

**Issue by sopedro** [ebanx/magento-gateway-ebanx#187]
I just downloaded the version 2.1 and no errors, but the calculation is wrong. the total amount of quote is $R 676,55 and im payment by Ebanx shows me $R2.697,74 with IOF. Same issue i had in previous version. I think this is because my base currency is EUR and the store view currency is in reais.

**Comment by sopedro** [comment]
I made some tests in sandbox and i know what happens, the extensions convert the cart total to reais but the problem is that the cart total already is in reais. The previous extension has an option to chose what currency will use (Frontend or base)...

**Comment by SparK-Cruz** [comment]
Hey @sopedro, that's correct, we use the base currency to convert the total to customer's local currency.
So if your store is showing prices in USD you can sell to any LatAm country, but it you use BRL only Brazil will be able to purchase through EBANX...

You said your store view is in BRL but base currency is EUR... we might be able to use the store view currency instead of base.

**Comment by SparK-Cruz** [comment]
There's one small problem there, the conversion rate might be different from ours.

**Comment by sopedro** [comment]
Hi, can you help to usealways the frontend currency instead of base currency? The old extension has an option that let me to choose ("Base Currency" or "FrontEndCurrency").

Thank you,

Pedro

**Comment by SparK-Cruz** [comment]
Hey... so we changed the code to use the store currency and added currency service as a currency rate provider for the currency configuration screen, so I guess the new version should fix it :)
